#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define SPLASH_STATE_SHOW_TIME 3
#define SPLASH_STATE_BACKGROUND_FILEPATH "Resources/SPLASH_BACKGROUND.png"

#define MAIN_MENU_STATE_BACKGROUND_FILEPATH "Resources/MAIN_MENU_BACKGROUND.png"
#define MAIN_MENU_STATE_TITLE_FILEPATH "Resources/MAIN_MENU_TITLE.png"
#define MAIN_MENU_PLAY_BUTTON_FILEPATH "Resources/PLAY_BUTTON.png"

#define GAME_STATE_BACKGROUND_FILEPATH "Resources/MAIN_MENU_BACKGROUND.png"
#define PAUSE_BUTTON "Resources/PAUSE_BUTTON.png"

#define PAUSE_STATE_BACKGROUND_FILEPATH "/home/draker/personal_projects/game_engine/Resources/MAIN_MENU_BACKGROUND.png"
#define RESUME_BUTTON "Resources/RESUME_BUTTON.png"
#define PAUSE_TITLE "Resources/PAUSED_TITLE.png"
#define EXIT_BUTTON "Resources/EXIT_GAME.png"

#define STATE_PLAYING 98
#define STATE_PAUSED 97
#define STATE_DRAW 96