#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define SPLASH_STATE_SHOW_TIME 3

#define SPLASH_STATE_BACKGROUND_FILEPATH "Resources/SPLASH_BACKGROUND.png"

#define MAIN_MENU_STATE_BACKGROUND_FILEPATH "Resources/MAIN_MENU_BACKGROUND.png"

#define MAIN_MENU_STATE_TITLE_FILEPATH "Resources/MAIN_MENU_TITLE.png"

#define MAIN_MENU_PLAY_BUTTON_FILEPATH "Resources/PLAY_BUTTON.png"