#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define TILESIZE 64

#define SPLASH_STATE_SHOW_TIME 3
#define SPLASH_STATE_BACKGROUND_FILEPATH "Resources/SPLASH_BACKGROUND.png"

#define MAIN_MENU_STATE_BACKGROUND_FILEPATH "Resources/MAIN_MENU_BACKGROUND.png"
#define MAIN_MENU_STATE_TITLE_FILEPATH "Resources/MAIN_MENU_TITLE.png"
#define MAIN_MENU_PLAY_BUTTON_FILEPATH "Resources/PLAY_BUTTON.png"

#define PAUSE_BUTTON "Resources/PAUSE_BUTTON.png"

#define PAUSE_STATE_BACKGROUND_FILEPATH "Resources/MAIN_MENU_BACKGROUND.png"
#define RESUME_BUTTON "Resources/RESUME_BUTTON.png"
#define PAUSE_TITLE "Resources/PAUSED_TITLE.png"
#define EXIT_BUTTON "Resources/EXIT_GAME.png"

#define GAME_STATE_BACKGROUND_FILEPATH "Resources/GAME_STATE_BACKGROUND.png"
#define AREA_ONE_BACKGROUND "Resources/AREA_ONE_BACKGROUND.png"
#define AREA_TWO_BACKGROUND "Resources/AREA_TWO_BACKGROUND.png"
#define AREA_THREE_BACKGROUND "Resources/AREA_THREE_BACKGROUND.png"
#define AREA_FOUR_BACKGROUND "Resources/AREA_FOUR_BACKGROUND.png"

#define PLAYER_SPRITE "Resources/PLAYER.png"
#define PLAYER_SPRITE_SHEET "Resources/PLAYER_SPRITE_SHEET.png"

#define STATE_PLAYING 98
#define STATE_PAUSED 97
#define STATE_DRAW 96